name: 'Generate Release Notes'
on:
  push:
    branches:
      - main
      - fix-ci
  schedule:
    - cron: '0 0 * * 0'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run:
    name: Run Script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: dist/.cache
          key: cache-dist
      - name: Setup Navi
        run: |
          ./public/install nightly
          echo "$HOME/.navi" >> $GITHUB_PATH
      - name: Generate Markdown
        run: |
          navi run script/generate-release.nv
      - uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          add-paths: |
            releases.md
          commit-message: |
            Update releases.md
